MINA_THE_HOLLOWER = "Mina The Hollower"
#items
ITEMS_OFFSET_PROGRESSIVES = 1000
ITEMS_OFFSET_KEARS = 2000
ITEMS_OFFSET_ABILITIES = 3000
ITEMS_OFFSET_BLOCKERS = 4000
ITEMS_OFFSET_TRAPS = 5000

#locations
LOCATIONS_OFFSET_BOSSES = 1000
LOCATIONS_OFFSET_GENERATORS = 2000

ASTRAL_ORRERY = "Astral Orrery"
QUEENSBURY_CRYPT = "Queensbury Crypt"
COLTRANE_PEAK = "Coltrane Peak"
SEPTEMBURG = "Septemburg"
BONE_BEACH = "Bone Beach"
NOXS_BAYOU = "Nox's Bayou"

repair_generator_indexes: dict[str, int] = {
    QUEENSBURY_CRYPT : 1,
    NOXS_BAYOU: 0,
    SEPTEMBURG: 2,
    BONE_BEACH: 3,
    COLTRANE_PEAK: 4,
    ASTRAL_ORRERY: 5
}



ALL_GENERATOR_KEYS = [QUEENSBURY_CRYPT, NOXS_BAYOU, SEPTEMBURG, BONE_BEACH, COLTRANE_PEAK, ASTRAL_ORRERY]

